#!/usr/bin/env python3

from subprocess import getoutput as sh
from argparse import ArgumentParser


def main():

    # Argument parser
    parser = ArgumentParser(description="KFM control tool")

    # Verbose
    verbose = {'args':['--verbose'],
               'kwargs':{'dest': 'verbose',
                         'action': 'store_true',
                         'default': False,
                         'help': 'extended output'}}

    command = {'args':['command'],
               'kwargs':{'action': 'store',
                         'nargs': '?',
                         'default': '',
                         'help': "command to run, with '{}' in place of parameters"}}

    command_args = {'args':['command_args'],
                    'kwargs':{'action': 'store',
                              'nargs': '*',
                              'default': [],
                              'help': "arguments to put into '{}'s (sorted by first appearence)"}}

    parser.add_argument(*verbose['args'], **verbose['kwargs'])
    parser.add_argument(*command['args'], **command['kwargs'])
    parser.add_argument(*command_args['args'], **command_args['kwargs'])

    args = parser.parse_args()

    if args.verbose:
        print(args)

    command = args.command.format(*args.command_args)

    print(command)
    print(sh(command))

if __name__ == "__main__":
    main()
 
#command='ffmpeg -re -i testsrc.avi -f v4l2 /dev/video1'
