#!/usr/bin/env python3

#    pip_upgrade
#
#    ----------------------------------------------------------------------
#    Copyright © 2018  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#


from subprocess import check_output as sh

output = str(sh(['pip', 'list', '--user'])).split("\\n")
packages = []

for p in output[2:]:
    if len(p.split()) == 2:
        package, version = p.split()
        packages.append({"name":package, "version":version})

for p in packages:
    print("Upgrade", p["name"], "? [Y/n]")
    ans = input()
    if ans.lower() in ("y", "\n"):
        print(sh(['pip', 'install', '-U', '--user', p['name']]))
