#!/bin/sh

su -c "content insert --uri content://settings/system --bind name:s:accelerometer_rotation --bind value:i:0"

su -c "content insert --uri content://settings/system --bind name:s:user_rotation --bind value:i:1"

#su -c "content insert --uri content://settings/system --bind name:s:accelerometer_rotation --bind value:i:1"
