#!/usr/bin/env bash

_ls_by_date() {
  local _path="${1}"
  # shellcheck disable=SC2012
  CLICOLORFORCE=1 \
    ls -lsht \
       --color "${_path}" | \
      less -r
}

_path="${1}"
_ls_by_date "${_path}"
